apiVersion: snapshot.storage.k8s.io/v1alpha1
kind: VolumeSnapshot
metadata:
  name: pvc1-snap
spec:
  snapshotClassName: csi-snapclass
  source:
    name: pv-claim-nas-ubuntu
    kind: PersistentVolumeClaim
